site:
  name: Signals | Kernels
  site: 'https://beta.signalskernels.com'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Signals | Kernels
    template: '%s — Signals | Kernels'
  description: 'Signals | Kernels transforms raw multimodal data into actionable intelligence through NLP, computer vision, audio analytics, and AI-powered solutions.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Signals | Kernels
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'G-3WFMPQL8Z8'

ui:
  theme: 'system'
